Move `Strict` to `Function.Strict` and move `_$!_` there
agda/agda-stdlib pull request #1533
Opened 2021-07-05 03:55 UTC by MatthewDaggitt

In response to #1486. Haven't yet cut the dependency of `Function.Base` on `Function.Strict` in order to preserve backwards compatibility.

2021-07-05 03:57 UTC, MatthewDaggitt commented
Question - should `Function` re-export `Function.Strict`?

2021-07-11 11:25 UTC, MatthewDaggitt commented
> Question - should Function re-export Function.Strict?

In the absence of any comment, I've gone with "yes".

2021-07-11 12:28 UTC, JacquesCarette requested changes
Other than a minor typo, this is great.

2021-07-11 12:28 UTC, JacquesCarette commented on src/Strict.agda
> +-- This module is DEPRECATED, please use `Data.Record` directly.
`Data.Record` ?

2021-07-11 12:32 UTC, MatthewDaggitt commented on src/Strict.agda
> +-- This module is DEPRECATED, please use `Data.Record` directly.
Thanks, good spot!

2021-07-13 01:14 UTC, merged