Add a proof of `n + suc m ≢ m` in `Data.Nat.Properties`
agda/agda-stdlib pull request #1598
Opened 2021-10-04 17:17 UTC by bafain

2021-10-04 17:33 UTC, MatthewDaggitt requested changes
Otherwise, again looks good, thanks for the PR!

2021-10-04 17:33 UTC, MatthewDaggitt commented on src/Data/Nat/Properties.agda
> +n+1+m≢m : ∀ m {n} → n + suc m ≢ m
To be consistent with naming conventions this should be called `m+1+n≢n`.

2021-10-04 23:07 UTC, bafain commented
Does the change follow the naming conventions now?

2021-10-05 12:15 UTC, MatthewDaggitt approved these changes

2021-10-05 12:15 UTC, merged