add take-[] and drop-[] to stdl Data/List/Properties.agda
agda/agda-stdlib pull request #1976
Opened 2023-06-12 14:51 UTC by Sofia-Insa

Add lemmas `take-[]` and `drop-[]`  to std library. In Data.List.Properties.

2023-06-12 16:10 UTC, JacquesCarette requested changes

2023-06-12 16:10 UTC, JacquesCarette commented on CHANGELOG.md
> +  take-[] : ∀ m → take {A = A} m [] ≡ []
Don't need the `{A = A}` in the CHANGELOG.

2023-06-12 16:45 UTC, JacquesCarette approved these changes

2023-06-13 00:16 UTC, MatthewDaggitt reviewed
Otherwise looks great! Thanks for the first PR.

2023-06-13 00:16 UTC, MatthewDaggitt commented on src/Data/List/Properties.agda
> +-- Taking and dropping from an empty list do nothing.
This comment should only reference `taking`, likewise the one below only `dropping`.

2023-06-13 00:16 UTC, MatthewDaggitt commented on src/Data/List/Properties.agda
> +take-[] ℕ.zero = refl
Can get rid of the `ℕ.` here and below as well.

2023-06-13 22:06 UTC, gallais commented on agda-stdlib
ugh?

2023-06-13 22:13 UTC, Sofia-Insa commented on agda-stdlib
Sorry, I got mixed up when I tried to do a new PR changes end up here. Didn't manage to delete a commit so I commit once more to delete the changes. 
There is only the add of take-[] and drop-[] in Data.List.Propreties and change in CHANGELOG.md that should appear now

2023-06-14 02:27 UTC, MatthewDaggitt commented
Err so it looks like now you've added the library as a git submodule of itself and then made the changes  in the submodule rather than the main library?!

2023-06-15 00:41 UTC, merged