Simplified `Vec` import in stdl
agda/agda-stdlib pull request #2018
Opened 2023-07-10 22:57 UTC by Sofia-Insa

Simplified `Vec` import in stdl
in `Data.Vec.Bounded` still import `Data.Vec` for `filter`, `takeWhile` and `dropWhile`

2023-07-13 19:24 UTC, JacquesCarette requested changes

2023-07-13 19:24 UTC, JacquesCarette commented on fix-whitespace.yaml
> -included-dirs:
this seems like an odd change to happen in this PR?

2023-07-13 19:24 UTC, JacquesCarette commented on src/Data/Vec/Bounded.agda
> +import Data.Vec as Vec using (filter; takeWhile; dropWhile)
As `Data.Vec` is still imported, probably revert this one.

2023-07-13 19:24 UTC, JacquesCarette commented on src/Data/Vec/Membership/Propositional/Properties.agda
> +open import Data.Vec hiding (here; there)
This breaks the 'alphabetical order' where no characters is less than any character. And also, there is no effective change. Please revert.

(Even better would be to remove the `hiding` and put in a proper `using`)

2023-07-28 13:45 UTC, gallais approved these changes

2023-07-29 11:44 UTC, JacquesCarette requested changes

2023-07-29 11:44 UTC, JacquesCarette commented on src/Data/Nat/Binary/Subtraction.agda
>  open import Data.Vec.Base using ([]; _∷_)
looks like the alphabetical ordering was inverted here?

2023-07-29 11:44 UTC, JacquesCarette commented on src/Data/Vec/Bounded.agda
> +open import Data.Vec as Vec using (Vec)
This looks like a regression, i.e. an import of a super-module where a sub-module used to be used?

2023-07-29 13:12 UTC, MatthewDaggitt commented
Thanks for the catches @JacquesCarette. Bad merge on my part

2023-07-31 12:03 UTC, JacquesCarette approved these changes

2023-07-31 12:09 UTC, Taneb requested changes

2023-07-31 12:09 UTC, Taneb commented on src/Tactic/RingSolver/Core/Polynomial/Semantics.agda
> +open import Data.Vec.Base          using (Vec; []; _∷_; uncons)
Alignment here has gone squiffy.

2023-07-31 12:13 UTC, Taneb approved these changes

2023-07-31 13:05 UTC, merged