Predicate transformers: Reconciling `Induction.RecStruct` with `Relation.Unary.PredicateTransformer.PT`, plus some `Container` relaxation
agda/agda-stdlib pull request #2140
Opened 2023-10-12 14:29 UTC by jamesmckinna

Addresses the first point in https://github.com/agda/agda-stdlib/issues/2083#issue-1889007083 plus some knock-on changes from the additional relaxed `Level`s available from taking `PT`-based definitions in place of the stricter `Pt`-based ones.

This PR is intended to be minimally invasive, ahead of a possible overhaul of `Induction.WellFounded`.

2023-11-04 19:38 UTC, jamesmckinna commented
More `CHANGELOG` hell.

2024-03-24 08:42 UTC, MatthewDaggitt requested changes
Otherwise looks good!

2024-03-24 08:42 UTC, MatthewDaggitt commented on src/Induction.agda
>          Recursor Rec
Could move this onto one line?

2024-03-24 08:42 UTC, MatthewDaggitt commented on src/Induction.agda
> +              SubsetRecursor Q Rec
Could move this onto one line?

2024-03-25 01:20 UTC, MatthewDaggitt approved these changes

2024-03-25 01:56 UTC, merged