[fixes #2178] regularise and specify/systematise, the conventions for symbol usage
agda/agda-stdlib pull request #2185
Opened 2023-10-26 15:30 UTC by jamesmckinna

2023-10-28 02:10 UTC, MatthewDaggitt requested changes

2023-10-28 02:10 UTC, MatthewDaggitt commented on notes/style-guide.md
> +  Unicode/emacs-input-method symbols neverthless can be rendered by
Typo: neverth**e**less

2023-10-28 02:10 UTC, MatthewDaggitt commented on notes/style-guide.md
> +#### Symbols for operators
Given the title above maybe this should "Symbols for operators and relations"?

2023-10-30 02:42 UTC, MatthewDaggitt approved these changes

2023-10-30 08:40 UTC, jamesmckinna commented
The diagnostic "0 checks passed" similar to that for #2183 ?

2023-11-01 03:14 UTC, merged