Qualified import of `PropositionalEquality` etc. fixing #2280
agda/agda-stdlib pull request #2293
Opened 2024-02-13 09:47 UTC by jamesmckinna

2024-02-13 21:43 UTC, JacquesCarette requested changes
Went for something like 105 tedious changes before hitting something that seemed like it could be improved. So close!

Hopefully your emacs-fu is strong because the tediousness of this is amazing.

2024-02-13 21:43 UTC, JacquesCarette commented on src/Relation/Binary/Indexed/Heterogeneous/Core.agda
> +import Relation.Binary.PropositionalEquality.Core as ≡
Is this import even needed if you didn't need to switch anything?

2024-02-13 21:43 UTC, JacquesCarette commented on src/Relation/Binary/Indexed/Heterogeneous/Bundles.agda
> -open import Relation.Binary.PropositionalEquality.Core as P using (_≡_)
I don't think this import is needed at all.

2024-02-13 21:43 UTC, JacquesCarette commented on src/Relation/Binary/Indexed/Heterogeneous/Definitions.agda
> +import Relation.Binary.PropositionalEquality.Core as ≡
This import doesn't seem to be needed either.

2024-02-13 21:43 UTC, JacquesCarette commented on src/Relation/Binary/Indexed/Homogeneous/Bundles.agda
> +open import Relation.Binary.PropositionalEquality.Core as ≡ using (_≡_)
Same here - not needed.

2024-02-13 21:43 UTC, JacquesCarette commented on src/Tactic/Cong.agda
> +open import Relation.Binary.PropositionalEquality.Core as ≡ using (_≡_; refl; cong)
Is the `as` even needed?

2024-02-14 10:10 UTC, jamesmckinna commented
Yes: `label:mindless` absolute apologies to anyone reviewing this. 
But thanks for your actual intelligence applied to this, and yes, the edits would improve.

2024-02-14 13:27 UTC, JacquesCarette approved these changes
Very nice set of improvements. Still tedious but no longer mindless!

2024-02-25 09:21 UTC, merged