Add `IsIdempotentMonoid` and `IsCommutativeBand` to `Algebra.Structures`
agda/agda-stdlib pull request #2402
Opened 2024-06-05 08:34 UTC by jamesmckinna

Fixes #2138 

NB:
* no `Biased` smart constructors to reflect equivalence with existing algebraic structure eg `(Semi)Lattice`
* no `Consequences` (ditto.)
* no `Bundles` (at this stage)

2024-06-05 12:59 UTC, Taneb commented
I think we should change `Algebra.Lattice` to refer to these structures somehow

2024-06-05 13:06 UTC, jamesmckinna commented
> I think we should change `Algebra.Lattice` to refer to these structures somehow

Downstream PR?

2024-06-05 14:00 UTC, MatthewDaggitt approved these changes

2024-06-05 17:16 UTC, jamesmckinna commented
Have redefined `IsSemilattice` and `IsBoundedSemilattice` as aliases for the new structures, but have *not* deprecated the old names (lots of knock-on viscosity elsewhere in the library).
Consider deprecation of the 'old' names as a downstream issue/PR?

2024-06-07 02:36 UTC, JacquesCarette approved these changes

2024-06-07 06:29 UTC, Taneb requested changes
I'm reviewing this in a train station, so I could be wrong, but I think you're missing that a commutative idempotent monoid is a commutative band?

And also IdempotentSemiring is missing... A lot of these, maybe now without be a good opportunity to add the links

2024-06-07 08:19 UTC, jamesmckinna commented on src/Algebra/Structures.agda
> +  isCommutativeBand = record { isBand = isBand ; comm = comm }
@Taneb So I think that this is what you were looking for?

2024-06-07 08:24 UTC, jamesmckinna commented
> I'm reviewing this in a train station, so I could be wrong, but I think you're missing that a commutative idempotent monoid is a commutative band?

See https://github.com/agda/agda-stdlib/blob/31193c68ea97c341062de656c56218937fca1b12/src/Algebra/Structures.agda#L250-L251

> And also IdempotentSemiring is missing... A lot of these, maybe now without be a good opportunity to add the links

Actually, I'm going to push back here and say these are (perhaps easy) downstream PRs, and I'm trying to avoid to much PR-creep these days in the interests of a tighter merge cycle... ?

Separately, I worry a bit about `IdempotentSemiring` as a name: do we intend (probably?) the `_+_` to be idempotent... in which case what do you call a `Semiring` in which `_*_` is idempotent?... and what's the relationship with `KleeneAlgebra`?

2024-06-07 08:52 UTC, jamesmckinna commented
> I'm reviewing this in a train station, so I could be wrong, but I think you're missing that a commutative idempotent monoid is a commutative band?

See comment above: L250-L251.

> And also IdempotentSemiring is missing... A lot of these, maybe now without be a good opportunity to add the links

Latest commit augments `IsIdempotentSemiring` with the relevant substructures (I hope! please check...).

After that, I'd be tempted to say that additional (sub)structures should be downstream PRs, unless you find any *glaring* omissions!?

2024-06-07 10:37 UTC, Taneb approved these changes

2024-06-07 12:00 UTC, jamesmckinna commented on src/Algebra/Structures.agda
> +  isCommutativeBand = record { isBand = isBand ; comm = comm }
Oops... `Bundles` as per original issue...

2024-06-07 13:34 UTC, JacquesCarette approved these changes

2024-06-07 14:10 UTC, merged