add `search` function to `Data.List.Relation.Unary.All`
agda/agda-stdlib pull request #2428
Opened 2024-07-04 13:10 UTC by jamesmckinna

fixes #989

2024-07-04 18:10 UTC, JacquesCarette commented
I'd approve if there were a CHANGELOG.

2024-07-04 19:13 UTC, jamesmckinna commented
> I'd approve if there were a CHANGELOG.

Currently all the v2.2-badged PRs I'm posting (or reviewing ;-)) are without `CHANGELOG`, against the inevitable reset after the eventual v2.1 release...

2024-07-07 21:29 UTC, mildsunrise commented
maybe it would ease some burden for everyone if we started special branches for every release, i.e. `v2.1`, and we could keep working on `master` for the next minor (or even major) release?

2024-07-08 06:19 UTC, Taneb requested changes

2024-07-08 06:19 UTC, Taneb commented on src/Data/List/Relation/Unary/All.agda
> +search P? = decide (Sum.swap ∘ (Dec.toSum ∘ P?))
Are the inner brackets necessary here? `∘` should be associative

2024-07-08 06:19 UTC, Taneb commented on src/Data/List/Relation/Unary/All.agda
> +open import Data.Sum.Base as Sum using (_⊎_;inj₁; inj₂)
```suggestion
open import Data.Sum.Base as Sum using (_⊎_; inj₁; inj₂)
```

2024-07-08 13:09 UTC, jamesmckinna commented
> maybe it would ease some burden for everyone if we started special branches for every release, i.e. `v2.1`, and we could keep working on `master` for the next minor (or even major) release?

That sounds good, so shoutout to the release-Meister @MatthewDaggitt for comment!? (The actual machinery of producing a release is still a bit mysterious to me...)

2024-07-08 13:20 UTC, Taneb approved these changes
Approved pending changelog

2024-07-11 02:13 UTC, MatthewDaggitt commented
Yup happy to create a release branch. We've never really had the quantity of contributors around a release time that made it a necessity before.

2024-07-11 10:01 UTC, jamesmckinna commented
> Yup happy to create a release branch. We've never really had the quantity of contributors around a release time that made it a necessity before.

But let's capitalise on the momentum that our new (and old!) contributors are bringing to the development process!?

2024-07-11 10:06 UTC, jamesmckinna commented
*contra* the approvals (for which all thanks), I'm wondering if a sharper lemma should be provable, namely that for `Decidable P`, we can exhibit a *view* of any given list `xs` as either `All (not P) xs` or `All (not P) ys` and `Any P zs` for a *prefix* decomposition `ys ++ zs` of `xs` (while trying to prove the equivalence of various definitions of `deleteFirst` against #988 ...)

2024-07-26 10:03 UTC, jamesmckinna commented
`CHANGELOG` entry added on the blank `v2.2-dev` template inherited from #2439 ... so a successful merge of that PR should see a more sensible diff/patch for this one...

2024-08-14 08:44 UTC, MatthewDaggitt approved these changes

2024-08-14 09:56 UTC, merged