Implement ≤-total in terms of _≤?_
agda/agda-stdlib pull request #2440
Opened 2024-07-19 08:15 UTC by Taneb

Fixes #2436

2024-07-19 09:01 UTC, gallais commented
You'll need a CHANGELOG entry

2024-07-19 09:44 UTC, Taneb commented
That's a good point, I'll add a changelog after #2439 gets merged

2024-07-27 09:37 UTC, JacquesCarette commented
I'll wait to do a proper review once the CHANGELOG is in place.

2024-08-15 12:58 UTC, jamesmckinna approved these changes
Modulo:
* `CHANGELOG`
* `breaking`

This looks great!

2024-08-26 10:56 UTC, jamesmckinna commented
How does this PR contribute to (positively or negatively...) the issues about 'concrete' orderings raised in issue #1179 ? 
It seems as though both are trying to tackle a pervasive problem; this PR, locally, with the bigger issue at a (more) global level.

2024-08-30 11:19 UTC, Taneb commented
@jamesmckinna they're related, but I don't think either of them solve or get in the way of the other

2024-09-01 11:40 UTC, jamesmckinna commented
I think when you resolve the merge conflict in `CHANGELOG`, you'll see a couple of entries from v2.1 which have crept in/been left in by mistake, and which should now be removed.

2024-09-01 13:04 UTC, JacquesCarette requested changes

2024-09-01 13:04 UTC, JacquesCarette commented on src/Data/Nat/Properties.agda
> +... | no  m≰n = inj₂ (≰⇒≥ m≰n)
You've improved the first case of this proof but not the second, as this still dispatches to a proof by recursion. Now laziness probably kicks in -- and yet, if you're worried about efficiency, shouldn't all the cases by made equally efficient?

2024-09-02 06:14 UTC, Taneb commented on src/Data/Nat/Properties.agda
> +... | no  m≰n = inj₂ (≰⇒≥ m≰n)
I think that anything that actually needs the value of the `m ≤ n` witness is going to need to do a proof by recursion to construct the value, including existing `_≤?_`. What matters here is the _decision_, whether we have `inj₁` or `inj₂`

2024-09-02 07:22 UTC, jamesmckinna commented on src/Data/Nat/Properties.agda
> +... | no  m≰n = inj₂ (≰⇒≥ m≰n)
Moreover, proofs of `_≤_` are irrelevant, so no client code should ever in poractice be exploiting the exact nature of the proof being computed. That said, there may be a way to concretise observation that via suitable use of `recompute`?

2024-09-02 07:38 UTC, Taneb commented on src/Data/Nat/Properties.agda
> +... | no  m≰n = inj₂ (≰⇒≥ m≰n)
I think adding an unnecessary `recompute` here would only confuse things...

2024-09-02 13:44 UTC, JacquesCarette commented on src/Data/Nat/Properties.agda
> +... | no  m≰n = inj₂ (≰⇒≥ m≰n)
I think "proofs of `_≤_` are irrelevant" is being abused for what it's not: yes, all such proofs are equal, BUT they still contain information (which can be extracted), namely the difference (as a Nat) between the numbers.

Irrelevant does not mean information-free.

2024-09-02 14:15 UTC, jamesmckinna commented on src/Data/Nat/Properties.agda
> +... | no  m≰n = inj₂ (≰⇒≥ m≰n)
I think I'd be groping towards something (esp. wit the mention of `recompute`) along the lines of: the implication `≰⇒≥` is based on a *negated* premise, which we know can have no computational content (cf. `Relation.Nullary.Recomputable`)... so while the conclusion `m ≥ n` indeed does have computational content (the difference), this can't arise *per se* from the proof of `m ≰ n`... so: either it *must* be by reference to the actual `m` and `n` concerned, or else that it, too, can be obtained by `recompute` from... something irrelevant. But I admit, it would be better if I had been able to demonstrate this, rather than speculate philosophically on the point.

2024-09-03 01:50 UTC, MatthewDaggitt commented
The question is do we view this as a backwards compatible breaking change? If it was just a change in behaviour then I would say yes and bump it to v3.0. If however, we argue that this is in fact a performance bug then the maybe we can justify adding it to v2.2?

2024-09-05 02:11 UTC, JacquesCarette commented on src/Data/Nat/Properties.agda
> +... | no  m≰n = inj₂ (≰⇒≥ m≰n)
Re: efficiency. I think I can see that.

2024-09-05 02:11 UTC, JacquesCarette approved these changes

2024-09-05 06:19 UTC, Taneb commented
@MatthewDaggitt while I would like it in sooner, of course, the position that has the better argument is that we don't make any performance guarantees at all (our readme says more or less this right near the beginning). Based on that, it probably ought wait for 3.0

2024-09-07 10:02 UTC, jamesmckinna commented
> @MatthewDaggitt while I would like it in sooner, of course, the position that has the better argument is that we don't make any performance guarantees at all (our readme says more or less this right near the beginning). Based on that, it probably ought wait for 3.0

Well, if you were to make that sacrifice, that would ease the path to a `v2.2` release following #2473 ...

2025-01-30 11:16 UTC, gallais commented on src/Data/Nat/Properties.agda
> +... | no  m≰n = inj₂ (≰⇒≥ m≰n)
Perhaps avoid using `yes` and `no`, cf. https://github.com/agda/agda-stdlib/pull/2365/files#r1566627871

2025-01-30 12:01 UTC, gallais approved these changes

2025-01-30 14:56 UTC, jamesmckinna commented on src/Data/Nat/Properties.agda
> +... | no  m≰n = inj₂ (≰⇒≥ m≰n)
Thanks for the shoutout, I've been wondering whether I've ridden that hobby-horse a bit too hard, but I do like the new, lazier versions.

2025-01-30 14:59 UTC, jamesmckinna commented
> Any objections to this being merged now?

Against our most recent discussion on the topic, we still do have a (placeholder?) non-`breaking` v2.3 milestone open, whereas `breaking` issues/PRs are typically being considered as v3.0? So maybe, ready though it may be, we can hold off merging for a bit? or is this mission critical to another project?

2025-02-04 15:20 UTC, JacquesCarette commented
Do we really wish to regard relying on reduction behaviour of *proofs* as 'breaking'? I completely agree that, given how Agda (MLTT, really) works, lots of proofs inevitably rely on the reduction behaviour of the terms they speak about. But lifting that up a level seems a bit too far? Do we have many theorems about properties of properties?

I suspect that this change would, in fact, not affect anyone. ['suspect' indicates lower confidence that 'bet' as I'm not a big gambler.]

2025-02-04 19:29 UTC, jamesmckinna commented
@JacquesCarette let me clarify my position:
* my understanding was that we had agreed that this was `breaking`, but I am happy if we row back on such a judgment
* my intention in  the above was to draw attention to PRs which are clearly non-`breaking`/v2.3, in contrast to those which might better/best be judged v3.0...

If everyone is happy, I'd merge this for v2.3, but would advise, for belt-and-braces, that there be a "non-backwards-compatible" entry in `CHANGELOG` to record what's happening?

2025-02-04 19:31 UTC, jamesmckinna commented
Or else, that we abandon the distinction v2.3/v3.0, and fast-forward to admit all the breaking changes? (We may have agreed that at the last maintainers' meeting, but for whatever reason, I'm dragging my heels...)

2025-02-08 17:49 UTC, merged