Proof that `pred` is right adjoint to `suc` on `ℕ._≤_`
agda/agda-stdlib pull request #2456
Opened 2024-08-13 07:17 UTC by jamesmckinna

I'm reluctant to add yet more to `Data.Nat.Properties`, but this lemma seemed missing, and offered a sweet-spot in an application I've been working on, and as a by-product permits refactoring of `≤-pred`.

2024-08-14 08:58 UTC, MatthewDaggitt requested changes
Other than that looks good!

2024-08-14 08:58 UTC, MatthewDaggitt commented on src/Data/Nat/Properties.agda
> +sm≤n⇒m≤pn : suc m ≤ n → m ≤ pred n
We usually use the full `suc` and `pred` in lemma names, i.e. `suc[m]≤n⇒m≤pred[n]`

2024-08-14 12:23 UTC, gallais approved these changes

2024-08-14 21:06 UTC, JacquesCarette approved these changes

2024-08-15 02:25 UTC, MatthewDaggitt approved these changes

2024-08-15 03:02 UTC, merged