Add `≤‴-irrelevant` to `Data.Nat.Properties`
agda/agda-stdlib pull request #2503
Opened 2024-11-23 05:35 UTC by tsung-ju

2024-11-23 07:38 UTC, jamesmckinna commented
Thanks for the proposed contribution.

Two quick comments in place of a proper review:
* besides 'completeness', what's the rationale for the addition? (this relation is rarely used in the library, and never, AFAIK, in a context where its being `Irrelevant` is important)
* the proofs do look very gnarly (esp. the use of `subst`), so I wonder if they can be simplified.

If we do agree to add this, you will need a `CHANGELOG` entry as well.

2024-11-23 09:49 UTC, jamesmckinna requested changes
Suggest adding the proof of `Irreflexive _≡_ _≤‴_` in order to make use of it.

Needs `CHANGELOG`.

2024-11-23 09:49 UTC, jamesmckinna commented on src/Data/Nat/Properties.agda
> +≤‴-irrelevant (≤‴-step p)   (≤‴-step q) rewrite ≤‴-irrelevant p q = refl
Suggest replacing the use of `rewrite` with one of `cong` (less strict; more robust):
```suggestion
≤‴-irrelevant (≤‴-step p)   (≤‴-step q) = cong ≤‴-step $ ≤‴-irrelevant p q
```

2024-11-23 09:49 UTC, jamesmckinna commented on src/Data/Nat/Properties.agda
> +≤‴-irrelevant (≤‴-step x<x) ≤‴-refl = contradiction (≤‴⇒≤ x<x) (<-irrefl refl)
These two clauses suggest a refactoring to abstract out an appeal to `Irreflexive _≡_ _≤‴_` as follows:
```suggestion
  lemma (≤‴-step m<m) e with () <‴-irrefl e m<m
≤‴-irrelevant (≤‴-step m<m) ≤‴-refl  with () <‴-irrefl refl m<m
```
with a prior definition (before L2240) as follows:
```agda
<‴-irrefl : Irreflexive _≡_ _<‴_
<‴-irrefl eq = <-irrefl eq ∘ ≤‴⇒≤
```

2024-11-23 18:24 UTC, tsung-ju commented
Hi, thanks for the feedback!

My use case for `m ≤‴ n` is to represent numbers with a lower bound `m`, using `≤‴-refl` and `≤‴-step` to adjust the lower bound. I needed irrelevance to prove decidable equality for a data structure containing these proofs. The proof was tricky under without-K, so I thought it might be a helpful addition. That said, I’m not opposed to deprecating or revising `_≤‴_`, as it can be difficult to work with in its current form.

I’ve addressed the easier suggestions and will update the CHANGELOG soon. I’ll also explore possible simplifications using `cast`.

2024-11-25 09:19 UTC, jamesmckinna commented
> I’ve addressed the easier suggestions and will update the CHANGELOG soon. I’ll also explore possible simplifications using `cast`.

This last part is *entirely* optional, except to draw your attention to the `subst` (fully general)/`cast` (specific on a per-type/-per-predicate/per-relation basis) distinction as a basis for 'subst-like' reasoning where matching on `refl` is actually doing too much, or the wrong kind of, evaluation (in particular, work that isn't erasable at run-time in a backend).

2024-11-29 17:28 UTC, jamesmckinna approved these changes

2024-12-02 02:30 UTC, MatthewDaggitt approved these changes

2024-12-02 02:31 UTC, MatthewDaggitt commented
Thanks for the contribution! Merging in now.

2024-12-02 03:09 UTC, merged